package org.sirohi.smartnotebook.controller;

import jakarta.validation.Valid;
import org.sirohi.smartnotebook.dto.*;
import org.sirohi.smartnotebook.service.ChatService;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.http.codec.ServerSentEvent;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Flux;

import java.net.URI;
import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api")
public class ChatController {

    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ChatController.class);
    private final ChatService chatService;

    public ChatController(ChatService chatService) {
        this.chatService = chatService;
    }

    // --- Chat lifecycle (scoped to notebook) ---

    @PostMapping("/notebooks/{notebookId}/chats")
    public ResponseEntity<ChatResponse> createChat(
            @PathVariable UUID notebookId,
            @RequestBody(required = false) ChatRequest request) {
        log.info("Received request to create chat for notebook: {}", notebookId);
        ChatRequest req = request != null ? request : new ChatRequest(null);
        ChatResponse chat = chatService.createChat(notebookId, req);
        log.info("Created chat with ID: {}", chat.id());
        return ResponseEntity
                .created(URI.create("/api/chats/" + chat.id()))
                .body(chat);
    }

    @GetMapping("/notebooks/{notebookId}/chats")
    public ResponseEntity<List<ChatResponse>> listChats(@PathVariable UUID notebookId) {
        log.debug("Listing chats for notebook: {}", notebookId);
        return ResponseEntity.ok(chatService.listChats(notebookId));
    }

    // --- Chat operations ---

    @GetMapping("/chats/{chatId}")
    public ResponseEntity<ChatResponse> getChat(@PathVariable UUID chatId) {
        log.debug("Retrieving chat: {}", chatId);
        return ResponseEntity.ok(chatService.getChatWithHistory(chatId));
    }

    @GetMapping("/chats/{chatId}/messages")
    public ResponseEntity<List<ChatMessageResponse>> getChatMessages(@PathVariable UUID chatId) {
        log.debug("Retrieving messages for chat: {}", chatId);
        return ResponseEntity.ok(chatService.getChatWithHistory(chatId).messages());
    }

    /** Blocking endpoint — waits for full LLM response before returning. */
    @PostMapping("/chats/{chatId}/messages")
    public ResponseEntity<ChatMessageResponse> sendMessage(
            @PathVariable UUID chatId,
            @Valid @RequestBody ChatMessageRequest request) {
        log.info("Received blocking message for chat: {}", chatId);
        ChatMessageResponse response = chatService.sendMessage(chatId, request);
        log.info("Sent blocking response for chat: {}", chatId);
        return ResponseEntity.ok(response);
    }

    /**
     * SSE streaming endpoint — streams tokens as they are generated by the LLM.
     * Client receives events: "token" (partial text) and "done" (citations +
     * metadata).
     */
    @PostMapping(value = "/chats/{chatId}/messages/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<ServerSentEvent<ChatTokenEvent>> streamMessage(
            @PathVariable UUID chatId,
            @Valid @RequestBody ChatMessageRequest request) {
        log.info("Received streaming message request for chat: {}", chatId);
        return chatService.sendMessageStreaming(chatId, request)
                .doOnComplete(() -> log.info("Completed streaming for chat: {}", chatId))
                .onErrorResume(e -> Flux.just(
                        ServerSentEvent.<ChatTokenEvent>builder()
                                .event("error")
                                .data(ChatTokenEvent.error(e.getMessage()))
                                .build()));
    }

    @DeleteMapping("/chats/{chatId}")
    public ResponseEntity<Void> deleteChat(@PathVariable UUID chatId) {
        log.info("Deleting chat: {}", chatId);
        chatService.deleteChat(chatId);
        return ResponseEntity.noContent().build();
    }
}
