spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: phi3:mini
      embedding:
        model: nomic-embed-text

  docker:
    compose:
      lifecycle-management: start-and-stop
      stop:
        command: down
